spring:
  database:
  url:
  username: test
  password:
  driver-class-name:
 jpa:
   database: mysql
   show_sql: true
   hibernate:
   ddl-auto: create

mail:
 host: smtp.gmail.com
  port: 587
  username: test.develhope@gmail.com
  password: rvckucwaswbzsejj
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
jackson:
  serialization:
    fail.on.empy-beans: false
